// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syekxqmzjiunzygfaxcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5ZWt4cW16aml1bnp5Z2ZheGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDUzODcsImV4cCI6MjA3MTM4MTM4N30.T5gLiHhg7ls0pgEUSPGTvLTCffYTJh0FVG8vIOkoQAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});